### ISSUE TITLE
upgrade_ha network failure after suspend

### ISSUE THREAD

**Issue by honvl** [PaloAltoNetworks/ansible-playbooks#12]
## Describe the bug

Timeout after suspending device in upgrade_ha,yml script

TASK [Suspend secondary device] ************************************************
06:14:44
114
task path: /tmp/awx_200_ybp_r6ni/project/upgrade_ha.yml:135
115
changed: [fw_py_pa3220-1_mgt.*] => {"changed": true, "msg": "Done", "stdout": "{\"response\": {\"@status\": \"success\", \"result\": \"Successfully changed HA state to suspended\"}}", "stdout_lines": ["{\"response\": {\"@status\": \"success\", \"result\": \"Successfully changed HA state to suspended\"}}"], "stdout_xml": "<response status=\"success\"><result>Successfully changed HA state to suspended</result></response>"}
116
117
TASK [Check that primary is now active] ****************************************
06:14:45
118
task path: /tmp/awx_200_ybp_r6ni/project/upgrade_ha.yml:140
119
changed: [fw_py_pa3220-1_mgt.*] => {"attempts": 1, "changed": true, "msg": "Done", "stdout": "{\"response\": {\"@status\": \"success\", \"result\": {\"enabled\": \"yes\", \"group\": {\"mode\": \"Active-Passive\", \"local-info\": {\"url-compat\": \"Mismatch\", \"app-version\": \"8311-6277\", \"gpclient-version\": \"4.1.2\", \"build-rel\": \"9.0.9-h1\", \"ha2-port\": \"ethernet1/19\", \"av-version\": \"3455-3966\", \"ha1-encrypt-enable\": \"no\", \"ha2-keep-alive\": \"log-only\", \"url-version\": \"0000.00.00.000\", \"ha1-backup-ipaddr\": \"172.16.34.1/30\", \"mgmt-hb\": \"configured\", \"platform-model\": \"PA-3220\", \"av-compat\": \"Match\", \"ha2-ipaddr\": \"192.168.0.200/24\", \"vpnclient-compat\": \"Match\", \"ha1-ipaddr\": \"172.16.33.1/24\", \"ha1-backup-macaddr\": \"e8:98:6d:d7:c4:07\", \"ha2-backup-ipaddr\": \"10.10.10.1/24\", \"vpnclient-version\": \"Not Installed\", \"ha2-macaddr\": \"e8:98:6d:d7:c4:52\", \"monitor-fail-holdup\": \"0\", \"priority\": \"98\", \"preempt-hold\": \"1\",…

TASK [Install target PAN-OS version and restart (secondary)] *******************
06:14:46
122
task path: /tmp/awx_200_ybp_r6ni/project/upgrade_ha.yml:151
123
fatal: [fw_py_pa3220-1_mgt.*]: FAILED! => {"changed": false, "msg": "Failed to check upgrade info due to generic communication error. Please check network connectivity and try again."}

## Expected behavior

Script should connect to suspended device successfully,

## Current behavior

Script sometimes times out when run on a device that has been suspended 1-2 seconds before.

## Possible solution

Pause for a few seconds, or check for ready before performing Install step on suspended device. 

## Steps to reproduce

Upgrade HA pair from 9.0.9-h1 to 9.1.3-h1

1.
2.
3.
4.

## Context

Failed to upgrade HA pair. Had to clone playbook and modify script with a pause.

## Your Environment

Ansible Tower 3.7.2 running in same datacenter as Palo Alto management interfaces

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by mrichardson03** [comment]
This is really working as intended.  The error message

```fatal: [fw_py_pa3220-1_mgt.*]: FAILED! => {"changed": false, "msg": "Failed to check upgrade info due to generic communication error. Please check network connectivity and try again."}```

was given by the firewall, and means the firewall had an issue communicating with the update server when checking for new updates.

**Comment by honvl** [comment]
I see. Perhaps the internet side of the firewall links have not 
converged yet for the newly active firewall, causing the secondary 
firewall to fail its connection to the update server.

------ Original Message ------

**Comment by mrichardson03** [comment]
That makes sense, especially if adding a pause resolved it for you.
