### ISSUE TITLE
Task "Install target PAN-OS version" fails. Upgrade still successful.

### ISSUE THREAD

**Issue by esplor** [PaloAltoNetworks/ansible-playbooks#13]
## Describe the bug

Every time I try to run playbook upgrade_single_major.yml or upgrade_single.yml, ansible runs through each task successfully until "Install target PAN-OS version".

Device(s) gets upgraded, then reboots, but after approx 20 minutes, seems to me when the device is up again. I get this error:
`TASK [Install target PAN-OS version] *****************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv.
The error was: socket.timeout: The read operation timed out
fatal: [brnn-pa220]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File \"/home/ansible/.ansible/tmp/ansible-tmp-1609968655.0812685-11601-66516665117439/AnsiballZ_panos_software.py\", line 102, in <module>
    _ansiballz_main()
  File \"/home/ansible/.ansible/tmp/ansible-tmp-1609968655.0812685-11601-66516665117439/AnsiballZ_panos_software.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/ansible/.ansible/tmp/ansible-tmp-1609968655.0812685-11601-66516665117439/AnsiballZ_panos_software.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_paloaltonetworks.panos.panos_software_payload_qrzrq9kx/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py\", line 199, in <module>
  File \"/tmp/ansible_paloaltonetworks.panos.panos_software_payload_qrzrq9kx/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py\", line 189, in main
  File \"/home/ansible/ansible/venv/lib/python3.7/site-packages/panos/base.py\", line 4233, in restart
    self.xapi.op(\"request restart system\", cmd_xml=True)
  File \"/home/ansible/ansible/venv/lib/python3.7/site-packages/panos/base.py\", line 3626, in method
    super_method(self, *args, **kwargs)
  File \"/home/ansible/ansible/venv/lib/python3.7/site-packages/pan/xapi.py\", line 951, in op
    self.__type_op(cmd, vsys, extra_qs)
  File \"/home/ansible/ansible/venv/lib/python3.7/site-packages/pan/xapi.py\", line 969, in __type_op
    response = self.__api_request(query)
  File \"/home/ansible/ansible/venv/lib/python3.7/site-packages/pan/xapi.py\", line 545, in __api_request
    response = urlopen(**kwargs)\n  File \"/usr/lib/python3.7/urllib/request.py\", line 222, in urlopen
    return opener.open(url, data, timeout)
  File \"/usr/lib/python3.7/urllib/request.py\", line 525, in open
    response = self._open(req, data)
  File \"/usr/lib/python3.7/urllib/request.py\", line 543, in _open
    '_open', req)
  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain
    result = func(*args)\n  File \"/usr/lib/python3.7/urllib/request.py\", line 1367, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File \"/usr/lib/python3.7/urllib/request.py\", line 1327, in do_open
    r = h.getresponse()
  File \"/usr/lib/python3.7/http/client.py\", line 1336, in getresponse
    response.begin()
  File \"/usr/lib/python3.7/http/client.py\", line 306, in begin
    version, status, reason = self._read_status()
  File \"/usr/lib/python3.7/http/client.py\", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")
  File \"/usr/lib/python3.7/socket.py\", line 589, in readinto
    return self._sock.recv_into(b)
  File \"/usr/lib/python3.7/ssl.py\", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File \"/usr/lib/python3.7/ssl.py\", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}`

 ## Your Environment
Devices are connected via S2S tunnel, remote device has dynamic WAN IP, tunnel is initiated from remote device.

- Version used:  ansible-playbook 2.10.4 | paloaltonetworks.panos 2.4.0
- Environment name and version: python 3.7.3 in virtual environment
- Operating System and version (desktop or mobile): Debian 10 in WSL2

**Comment by mrichardson03** [comment]
There's not much I can do in a playbook to fix an OS socket timeout.  These playbooks have been well tested with a PA-220 and Debian (technically Raspbian), so I would look into if WSL is doing something strange.

**Comment by esplor** [comment]
Thanks, the next time I upgrade a firewall I will try on a physical Debian box instead of using Debian in WSL2.

I thought it might be related to `restart: true` in task "Install target PAN-OS version"

```
    - name: Install target PAN-OS version
      paloaltonetworks.panos.panos_software:
        provider: '{{ device }}'
        version: '{{ version }}'
        restart: true
```

**Comment by mwisniewski9** [comment]
I hate to revive an old issue but I experienced the exact same behavior when running the upgrade_single.yml playbook on a production PA-220 firewall. When running on a PA-220 in my lab environment this did not occur but the configuration was slightly different but still used the same base PAN-OS of 8.0.2.  

Next time I run this playbook, I will attach the verbose output

Version used: ansible-playbook 2.9.18 | paloaltonetworks.panos 2.6.0
Environment name and version: python 3.6. 
Operating System and version (desktop or mobile): RHEL 8.3.1-5
