### ISSUE TITLE
Suggestion for example, How to use gatheredfilter, for example to update rules/addressgroup

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/ansible-playbooks#167]
I have found this quite messy to understand, updating rules/addressgroup etc is a quite common task so it would be good with some examples

**Comment by jamesholland-uk** [comment]
Hi @ishuguru, does this [help](https://pan.dev/ansible/docs/panos/guides/search-and-remove/)?

**Comment by ishuguru** [comment]
Yes that helped, i did a bit modification so im able to enter the ip of the object insted (since we unfortunately has alot of duplicate object), and it loop through with       
with_nested: 

Next is trying to remove the object from security rules the same way :)

**Comment by jamesholland-uk** [comment]
Thanks for confirming 👍
