### ISSUE TITLE
need help on creating address objects , address ranges and fqdn

### ISSUE THREAD

**Issue by asgr8e** [PaloAltoNetworks/ansible-playbooks#184]
I just want to know what all parameters address_type can take ??

**Comment by jamesholland-uk** [comment]
Hi @asgr8e, this can be found in the [documentation](https://paloaltonetworks.github.io/pan-os-ansible), specifically [here](https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_address_object_module.html) for the address_group module: "ip-netmask", "ip-range", "fqdn" or "ip-wildcard"
