### ISSUE TITLE
Need to put condition if interface is "none" put the default value of interface (none) else take the data from csv file 

### ISSUE THREAD

**Issue by asgr8e** [PaloAltoNetworks/ansible-playbooks#192]
Hi, is there any way I can create a condition if interface is mentioned none to enter default value of interface (none) because mentioning none manually is not working, while creating static routes

below is my code 

---
# fw_objects.yml - Create various objects on a PAN-OS device.

- hosts: 'palo'
  connection: local

  vars:
    device:
      ip_address: '192.168.1.139'
      username: 'an'
      password: 'Co'
      api_key: 'LUFRPT1qWnhc08xT2gyeHN0N0FyVlhXYWMyRWY2eVdSMlRRdXlKVzhvQ0tvVnFXZ2xBbWtoNEd0VmlyTTV5bg=='

  tasks:
    - name: Read CSV file
      ansible.builtin.set_fact:
        csv_data: "{{ lookup('file','/home/controller/ansible-projects/route.csv').splitlines()[1:] }}"

    - name: Create route
      paloaltonetworks.panos.panos_static_route:
         provider: '{{ device }}'
         name: "{{ item.split(',')[0] }}"
         destination: "{{ item.split(',')[1] }}"
         template: "{{ item.split(',')[2] }}"
         virtual_router: "{{ item.split(',')[3] }}"
         nexthop_type: "{{ item.split(',')[4] }}"
         nexthop: "{{ item.split(',')[5] }}"
         #interface: "{{ item.split(',')[6] }}"
         metric: "{{ item.split(',')[7] }}"
         commit: true
      loop: "{{ csv_data }}"
      when: "item.split(',')[6] == 'none'"
    - name: Create route
      paloaltonetworks.panos.panos_static_route:
         provider: '{{ device }}'
         name: "{{ item.split(',')[0] }}"
         destination: "{{ item.split(',')[1] }}"
         template: "{{ item.split(',')[2] }}"
         virtual_router: "{{ item.split(',')[3] }}"
         nexthop_type: "{{ item.split(',')[4] }}"
         nexthop: "{{ item.split(',')[5] }}"
         interface: "{{ item.split(',')[6] }}"
         metric: "{{ item.split(',')[7] }}"
         commit: true
      loop: "{{ csv_data }}"

**Comment by jamesholland-uk** [comment]
Hi @asgr8e, in Ansible you can use something like he below, where you can specify a variable name (`variable_a`), and a default for the value if the variable is not defined:

my_variable: '{{ variable_a | default("default value if variable_a is not defined") }}'

This is a general Ansible question not specific to the PAN-OS collection, and if you need more information I would suggest asking in Ansible's community areas.
