### ISSUE TITLE
failure in upgrade_panorama_ha script

### ISSUE THREAD

**Issue by honvl** [PaloAltoNetworks/ansible-playbooks#20]
Upgrading from Panorama 9.1.3-h1 to 9.1.8

This task doesn't work:

TASK [Check that primary is up and passive] ************************************
task path: /tmp/awx_578_b2v3d6wh/project/upgrade_panorama_ha.yml:68
FAILED - RETRYING: Check that primary is up and passive (30 retries left).
FAILED - RETRYING: Check that primary is up and passive (29 retries left).
FAILED - RETRYING: Check that primary is up and passive (28 retries left).
FAILED - RETRYING: Check that primary is up and passive (27 retries left).
........all the way to 0

Command line shows:

admin@pypan01(primary-passive)> show high-availability state

High-Availability:
  Local Information:
    Version: 1
    State: primary-passive (last 46 minutes)
    Device Information:
      Management IPv4 Address: x.x.x.x/24; MAC: xxxxxxxx
      Management IPv6 Address: 
      Link Monitor Interval: 3000 ms
      Encryption Enabled: no
    Election Option Information:
      Priority: primary
      Preemptive: no
    Version Compatibility:
      Software Version: Mismatch
      Application Content Compatibility: Match
      Anti-Virus Compatibility: Match
  Peer Information:
    Connection status: up
    Version: 1
    State: secondary-active (last 46 minutes)
    Device Information:
      Management IPv4 Address: x.x.x.x; MAC: xxxxxxxxxxxx
      Connection up; Primary HA1 link
    Election Option Information:
      Priority: secondary
      Preemptive: no
  Configuration Synchronization:
    Enabled: yes
    Running Configuration: not synchronized
      Out-of-sync Reason: Started with config out-of-sync

**Comment by mrichardson03** [comment]
Working as expected.  Config is not synchronized, so the playbook stopped.
