### ISSUE TITLE
PA-7080 Chassis-Ready Doesn't Exist

### ISSUE THREAD

**Issue by luigixp** [PaloAltoNetworks/ansible-playbooks#78]
This script doesn't seem to work with 7000 series, since the command "show chassis-ready" doesn't exist.
Is there another method to get the same result to check chassis or something similar to verify device is back up after reboot?

The device should be upgraded, and then reboot, and script continues to check if device is back up. However it can't run the show chassis-ready command since doesn't exist on 7000 series device.

Script attempts to run the show chassis-ready command but doesn't exist on 7000 series device.

Use another command that exist on 7000 series or check for 7000 series or skip this check for 7000 series.

Run on a 7000 series palo alto firewall.

1.
2.
3.
4.

## Context

Two 7080 firewall devices in HA.

- Version used: 9.1.10 to 9.1.11
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python 3.8.11
- Operating System and version (desktop or mobile): Ubuntu 18.04.5 LTS
- Link to your project:

**Comment by mrichardson03** [comment]
That command could be swapped out with a `panos_check` module call to see if the autocomplete has finished, but I don't have access to a pair of 7000s to test.

**Comment by luigixp** [comment]
- name: Chassis ready (primary)
      paloaltonetworks.panos.panos_op:
        provider: '{{ primary }}'
        cmd: 'show chassis-ready'
      changed_when: false
      register: result
      until: result is not failed and (result.stdout | from_json).response.result == 'yes'
      retries: 30
      delay: 60


Can you give an example, would it be a simple modify of the above?
